version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass 
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - /db_data:/var/lib/postgresql/data
    restart: always
  # web:
  #   build: .
  #   ports:
  #     - "80:3000"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_HOST: db
  #   restart: always
volumes:
  db_data:
